import { WORKFLOW_FAMILIES, SPECIALTIES as CORE_SPECIALTIES } from './specialtyCatalog'

const familyDefaults = {
  AESTHETICS: { planLabel: 'Treatment plan', planPlural: 'Treatment plans', allowedKinds: ['LASER_HAIR_REMOVAL', 'GENERAL'] },
  BEAUTY: { planLabel: 'Service plan', planPlural: 'Service plans', allowedKinds: ['GENERAL'] },
  REHAB: { planLabel: 'Care plan', planPlural: 'Care plans', allowedKinds: ['CARE', 'GENERAL'] },
  FITNESS: { planLabel: 'Training plan', planPlural: 'Training plans', allowedKinds: ['FITNESS'] },
  WELLNESS: { planLabel: 'Wellness plan', planPlural: 'Wellness plans', allowedKinds: ['CARE', 'GENERAL'] },
  COACHING: { planLabel: 'Goal plan', planPlural: 'Goal plans', allowedKinds: ['GENERAL', 'CARE'] },
  BODYWORK: { planLabel: 'Recovery plan', planPlural: 'Recovery plans', allowedKinds: ['CARE', 'GENERAL'] },
  CONSULTING: { planLabel: 'Engagement', planPlural: 'Engagements', allowedKinds: ['GENERAL'] },
  CARE: { planLabel: 'Client plan', planPlural: 'Client plans', allowedKinds: ['CARE', 'GENERAL'] },
}

function add(key, label, family, aliases = [], samplePlans = []) {
  const defaults = familyDefaults[family] || familyDefaults.CARE
  return { key, label, family, aliases, ...defaults, placeholder: `e.g. ${samplePlans[0] || `${label} client plan`}`, samplePlans: samplePlans.length ? samplePlans : [`${label} client plan`, 'Progress & follow-up'] }
}

const EXPANDED_SPECIALTIES = [
  add('ACNE_SPECIALIST','Acne Specialist','AESTHETICS',['acne esthetician'],['Acne clearing program','Skin response history']),
  add('FACIALIST','Facialist','AESTHETICS',['facial specialist'],['Facial treatment series','Skin maintenance']),
  add('DERMAPLANING_SPECIALIST','Dermaplaning Specialist','AESTHETICS',['dermaplaning'],['Dermaplaning series','Skin response follow-up']),
  add('MICRONEEDLING_SPECIALIST','Microneedling Specialist','AESTHETICS',['microneedling'],['Microneedling series','Recovery follow-up']),
  add('CHEMICAL_PEEL_SPECIALIST','Chemical Peel Specialist','AESTHETICS',['peel specialist'],['Peel treatment series','Post-peel recovery']),
  add('BODY_CONTOURING_SPECIALIST','Body Contouring Specialist','AESTHETICS',['body sculpting'],['Body contouring series','Measurement progress']),
  add('CRYOTHERAPY_SPECIALIST','Cryotherapy Specialist','AESTHETICS',['cryotherapy'],['Cryotherapy series','Response follow-up']),
  add('RED_LIGHT_THERAPY_PROVIDER','Red Light Therapy Provider','AESTHETICS',['red light therapy'],['Light therapy series','Response history']),
  add('IV_HYDRATION_PROVIDER','IV Hydration Provider','AESTHETICS',['iv hydration'],['Hydration visit plan','Follow-up history']),
  add('TEETH_WHITENING_SPECIALIST','Teeth Whitening Specialist','AESTHETICS',['teeth whitening'],['Whitening service plan','Shade progress']),
  add('MICROBLADING_ARTIST','Microblading Artist','BEAUTY',['microblading'],['Brow service plan','Touch-up history']),
  add('TATTOO_ARTIST','Tattoo Artist','BEAUTY',['tattooer'],['Tattoo project','Healing follow-up']),
  add('PIERCER','Professional Piercer','BEAUTY',['body piercer'],['Piercing service history','Healing follow-up']),
  add('WIG_SPECIALIST','Wig Specialist','BEAUTY',['wig stylist'],['Wig fitting plan','Maintenance history']),
  add('HAIR_EXTENSION_SPECIALIST','Hair Extension Specialist','BEAUTY',['extension stylist'],['Extension maintenance','Install history']),
  add('COLORIST','Hair Colorist','BEAUTY',['color specialist'],['Color maintenance','Formula history']),
  add('CURL_SPECIALIST','Curly Hair Specialist','BEAUTY',['curl stylist'],['Curl care plan','Product & service history']),
  add('SCALP_SPECIALIST','Scalp Care Specialist','BEAUTY',['scalp care'],['Scalp care plan','Service response history']),
  add('BRIDAL_STYLIST','Bridal Hair Stylist','BEAUTY',['bridal stylist'],['Bridal style plan','Trial & event notes']),
  add('IMAGE_CONSULTANT','Image Consultant','BEAUTY',['personal image consultant'],['Style direction','Wardrobe milestones']),
  add('RESPIRATORY_THERAPIST','Respiratory Therapist','REHAB',['rt'],['Respiratory care goals','Home routine progress']),
  add('HAND_THERAPIST','Hand Therapist','REHAB',['certified hand therapist'],['Hand function plan','Mobility progress']),
  add('VESTIBULAR_THERAPIST','Vestibular Therapist','REHAB',['vestibular therapy'],['Balance rehab plan','Symptom progress']),
  add('LYMPHEDEMA_THERAPIST','Lymphedema Therapist','REHAB',['lymphedema therapy'],['Management plan','Measurement progress']),
  add('CARDIAC_REHAB_SPECIALIST','Cardiac Rehabilitation Specialist','REHAB',['cardiac rehab'],['Rehab progression','Activity milestones']),
  add('PULMONARY_REHAB_SPECIALIST','Pulmonary Rehabilitation Specialist','REHAB',['pulmonary rehab'],['Pulmonary rehab plan','Activity tolerance']),
  add('NEURO_REHAB_SPECIALIST','Neurological Rehabilitation Specialist','REHAB',['neuro rehab'],['Functional rehab plan','Milestone progress']),
  add('PEDIATRIC_OT','Pediatric Occupational Therapist','REHAB',['pediatric ot'],['Daily skills plan','Functional milestones']),
  add('PEDIATRIC_PT','Pediatric Physical Therapist','REHAB',['pediatric pt'],['Mobility plan','Development milestones']),
  add('AUDIOLOGIST','Audiologist','CARE',['hearing specialist'],['Hearing support plan','Device follow-up']),
  add('PERSONAL_TRAINING_GYM','Gym Personal Trainer','FITNESS',['gym trainer'],['Strength program','Training milestones']),
  add('ONLINE_FITNESS_COACH','Online Fitness Coach','FITNESS',['online trainer'],['Remote training plan','Weekly check-ins']),
  add('BODYBUILDING_COACH','Bodybuilding Coach','FITNESS',['physique coach'],['Prep training block','Physique progress']),
  add('POWERLIFTING_COACH','Powerlifting Coach','FITNESS',['powerlifting'],['Meet prep block','Strength milestones']),
  add('OLYMPIC_WEIGHTLIFTING_COACH','Olympic Weightlifting Coach','FITNESS',['weightlifting coach'],['Competition prep','Lift progression']),
  add('CROSSFIT_COACH','CrossFit Coach','FITNESS',['crossfit trainer'],['Performance cycle','Benchmark progress']),
  add('TRIATHLON_COACH','Triathlon Coach','FITNESS',['tri coach'],['Race build','Training load progress']),
  add('CYCLING_COACH','Cycling Coach','FITNESS',['bike coach'],['Cycling training block','Power milestones']),
  add('SWIM_COACH','Swimming Coach','FITNESS',['swimming instructor'],['Swim progression','Technique milestones']),
  add('TENNIS_COACH','Tennis Coach','FITNESS',['tennis instructor'],['Tennis development plan','Skill milestones']),
  add('GOLF_COACH','Golf Coach','FITNESS',['golf instructor'],['Swing development','Performance milestones']),
  add('BOXING_COACH','Boxing Coach','FITNESS',['boxing trainer'],['Boxing development plan','Conditioning progress']),
  add('MARTIAL_ARTS_INSTRUCTOR','Martial Arts Instructor','FITNESS',['martial arts coach'],['Skill progression','Belt milestones']),
  add('DANCE_INSTRUCTOR','Dance Instructor','FITNESS',['dance teacher'],['Technique plan','Performance milestones']),
  add('GYMNASTICS_COACH','Gymnastics Coach','FITNESS',['gymnastics instructor'],['Skill progression','Routine milestones']),
  add('PICKLEBALL_COACH','Pickleball Coach','FITNESS',['pickleball instructor'],['Skill development','Match progress']),
  add('POSTPARTUM_FITNESS_COACH','Postpartum Fitness Coach','FITNESS',['postpartum trainer'],['Return-to-fitness plan','Strength progress']),
  add('PRENATAL_FITNESS_COACH','Prenatal Fitness Coach','FITNESS',['prenatal trainer'],['Prenatal movement plan','Weekly progress']),
  add('CORPORATE_WELLNESS_COACH','Corporate Wellness Coach','WELLNESS',['workplace wellness'],['Workplace wellness plan','Participation progress']),
  add('HABIT_COACH','Habit Coach','WELLNESS',['habit coaching'],['Habit-building plan','Consistency check-ins']),
  add('STRESS_MANAGEMENT_COACH','Stress Management Coach','WELLNESS',['stress coach'],['Stress support plan','Coping routine progress']),
  add('MINDFULNESS_COACH','Mindfulness Coach','WELLNESS',['mindfulness teacher'],['Mindfulness practice','Reflection progress']),
  add('MEDITATION_TEACHER','Meditation Teacher','WELLNESS',['meditation coach'],['Meditation practice plan','Practice consistency']),
  add('BREATHWORK_FACILITATOR','Breathwork Facilitator','WELLNESS',['breathwork coach'],['Breathwork practice','Session reflections']),
  add('AYURVEDIC_WELLNESS_COACH','Ayurvedic Wellness Coach','WELLNESS',['ayurveda coach'],['Lifestyle routine plan','Wellness check-ins']),
  add('FUNCTIONAL_NUTRITION_COACH','Functional Nutrition Coach','WELLNESS',['functional nutrition'],['Nutrition routine plan','Food habit progress']),
  add('SPORTS_NUTRITION_COACH','Sports Nutrition Coach','WELLNESS',['sports nutrition'],['Performance nutrition plan','Fueling check-ins']),
  add('WEIGHT_MANAGEMENT_COACH','Weight Management Coach','WELLNESS',['weight coach'],['Sustainable habits plan','Progress check-ins']),
  add('SOBRIETY_COACH','Sobriety Coach','COACHING',['recovery coach'],['Recovery goals','Accountability check-ins']),
  add('PARENT_COACH','Parent Coach','COACHING',['parenting coach'],['Parenting goals','Family routine actions']),
  add('DIVORCE_COACH','Divorce Coach','COACHING',['separation coach'],['Transition plan','Decision milestones']),
  add('DATING_COACH','Dating Coach','COACHING',['dating consultant'],['Dating goals','Reflection milestones']),
  add('CONFIDENCE_COACH','Confidence Coach','COACHING',['self confidence coach'],['Confidence goals','Action milestones']),
  add('MINDSET_COACH','Mindset Coach','COACHING',['mindset coaching'],['Mindset goals','Reflection progress']),
  add('PRODUCTIVITY_COACH','Productivity Coach','COACHING',['productivity coaching'],['Execution system','Weekly priorities']),
  add('TIME_MANAGEMENT_COACH','Time Management Coach','COACHING',['time coach'],['Time management system','Weekly review']),
  add('CREATIVITY_COACH','Creativity Coach','COACHING',['creative coach'],['Creative project goals','Momentum check-ins']),
  add('WRITING_COACH','Writing Coach','COACHING',['author coach'],['Writing project plan','Draft milestones']),
  add('PUBLIC_SPEAKING_COACH','Public Speaking Coach','COACHING',['speaking coach'],['Speaking development','Presentation milestones']),
  add('COMMUNICATION_COACH','Communication Coach','COACHING',['communications coach'],['Communication goals','Practice milestones']),
  add('SALES_COACH','Sales Coach','COACHING',['sales coaching'],['Sales development plan','Pipeline habits']),
  add('REAL_ESTATE_COACH','Real Estate Coach','COACHING',['realtor coach'],['Production plan','Pipeline milestones']),
  add('SPIRITUAL_COACH','Spiritual Coach','COACHING',['spiritual coaching'],['Personal practice goals','Reflection milestones']),
  add('GRIEF_COACH','Grief Coach','COACHING',['grief support coach'],['Support goals','Reflection check-ins']),
  add('SOMATIC_PRACTITIONER','Somatic Practitioner','BODYWORK',['somatic therapy practitioner'],['Somatic support plan','Session response']),
  add('ROLFING_PRACTITIONER','Structural Integration Practitioner','BODYWORK',['rolfing'],['Structural integration series','Movement response']),
  add('MYOFASCIAL_RELEASE_THERAPIST','Myofascial Release Therapist','BODYWORK',['myofascial therapist'],['Release treatment plan','Mobility response']),
  add('REFLEXOLOGIST','Reflexologist','BODYWORK',['reflexology'],['Reflexology series','Session response']),
  add('REIKI_PRACTITIONER','Reiki Practitioner','BODYWORK',['reiki'],['Session plan','Wellbeing reflections']),
  add('ACUPRESSURE_PRACTITIONER','Acupressure Practitioner','BODYWORK',['acupressure'],['Acupressure plan','Response history']),
  add('CUPPING_THERAPIST','Cupping Therapist','BODYWORK',['cupping'],['Cupping series','Recovery response']),
  add('MOBILITY_STRETCH_PRACTITIONER','Assisted Stretch Practitioner','BODYWORK',['assisted stretching'],['Stretch series','Mobility progress']),
  add('HR_CONSULTANT','Human Resources Consultant','CONSULTING',['hr consultant'],['People operations engagement','Implementation milestones']),
  add('OPERATIONS_CONSULTANT','Operations Consultant','CONSULTING',['ops consultant'],['Operations improvement','Delivery milestones']),
  add('STRATEGY_CONSULTANT','Strategy Consultant','CONSULTING',['strategy advisor'],['Strategy engagement','Decision milestones']),
  add('MANAGEMENT_CONSULTANT','Management Consultant','CONSULTING',['management advisor'],['Management engagement','Delivery milestones']),
  add('BRAND_CONSULTANT','Brand Consultant','CONSULTING',['brand strategist'],['Brand strategy','Launch milestones']),
  add('SOCIAL_MEDIA_CONSULTANT','Social Media Consultant','CONSULTING',['social media strategist'],['Content strategy','Campaign milestones']),
  add('SEO_CONSULTANT','SEO Consultant','CONSULTING',['search consultant'],['SEO roadmap','Ranking milestones']),
  add('UX_CONSULTANT','UX Consultant','CONSULTING',['user experience consultant'],['UX engagement','Research milestones']),
  add('CYBERSECURITY_CONSULTANT','Cybersecurity Consultant','CONSULTING',['security consultant'],['Security improvement plan','Risk milestones']),
  add('CLOUD_CONSULTANT','Cloud Consultant','CONSULTING',['cloud architect'],['Cloud modernization','Migration milestones']),
  add('DATA_CONSULTANT','Data & Analytics Consultant','CONSULTING',['data consultant'],['Analytics roadmap','Delivery milestones']),
  add('AI_CONSULTANT','AI Consultant','CONSULTING',['artificial intelligence consultant'],['AI adoption roadmap','Pilot milestones']),
  add('PROJECT_MANAGEMENT_CONSULTANT','Project Management Consultant','CONSULTING',['pm consultant'],['Delivery plan','Project milestones']),
  add('NONPROFIT_CONSULTANT','Nonprofit Consultant','CONSULTING',['nonprofit advisor'],['Organization roadmap','Program milestones']),
  add('FUNDRAISING_CONSULTANT','Fundraising Consultant','CONSULTING',['development consultant'],['Fundraising plan','Campaign milestones']),
  add('EDUCATION_CONSULTANT','Education Consultant','CONSULTING',['education advisor'],['Education engagement','Program milestones']),
  add('COLLEGE_ADMISSIONS_CONSULTANT','College Admissions Consultant','CONSULTING',['admissions coach'],['Application plan','Admissions milestones']),
  add('WEDDING_PLANNER','Wedding Planner','CONSULTING',['wedding coordinator'],['Wedding project plan','Planning milestones']),
  add('EVENT_PLANNER','Event Planner','CONSULTING',['event coordinator'],['Event project plan','Planning milestones']),
  add('INTERIOR_DESIGNER','Interior Designer','CONSULTING',['interior decorator'],['Design project','Room milestones']),
  add('HOME_STAGER','Home Stager','CONSULTING',['staging consultant'],['Staging project','Room milestones']),
  add('VIRTUAL_ASSISTANT','Virtual Assistant','CONSULTING',['va'],['Client operations plan','Weekly deliverables']),
  add('BOOKKEEPER','Bookkeeper','CONSULTING',['bookkeeping'],['Books cleanup plan','Monthly close milestones']),
  add('TAX_PREPARER','Tax Preparer','CONSULTING',['tax professional'],['Tax preparation engagement','Filing milestones']),
  add('CREDIT_COACH','Credit Coach','CONSULTING',['credit consultant'],['Credit improvement plan','Score milestones']),
  add('DEBT_COACH','Debt Coach','CONSULTING',['debt counselor'],['Debt payoff plan','Monthly milestones']),
  add('MORTGAGE_COACH','Mortgage Readiness Coach','CONSULTING',['homebuyer coach'],['Mortgage readiness plan','Application milestones']),
  add('POSTPARTUM_DOULA','Postpartum Doula','CARE',['postpartum support'],['Postpartum support plan','Family check-ins']),
  add('NEWBORN_CARE_SPECIALIST','Newborn Care Specialist','CARE',['newborn specialist'],['Newborn care plan','Family follow-up']),
  add('SLEEP_CONSULTANT_BABY','Pediatric Sleep Consultant','CARE',['baby sleep consultant'],['Sleep support plan','Routine progress']),
  add('CHILDBIRTH_EDUCATOR','Childbirth Educator','CARE',['birth educator'],['Birth education plan','Preparation milestones']),
  add('FERTILITY_COACH','Fertility Coach','CARE',['fertility support'],['Fertility support plan','Cycle check-ins']),
  add('CAREGIVER_COACH','Caregiver Coach','CARE',['caregiver support'],['Caregiver support plan','Wellbeing check-ins']),
  add('PATIENT_ADVOCATE','Patient Advocate','CARE',['health advocate'],['Advocacy plan','Care coordination milestones']),
  add('AGING_LIFE_CARE_MANAGER','Aging Life Care Manager','CARE',['geriatric care manager'],['Care coordination plan','Family milestones']),
  add('SPECIAL_NEEDS_ADVOCATE','Special Needs Advocate','CARE',['disability advocate'],['Advocacy plan','Service milestones']),
  add('AUTISM_SUPPORT_SPECIALIST','Autism Support Specialist','CARE',['autism coach'],['Support plan','Routine progress']),
  add('EXECUTIVE_FUNCTION_COACH','Executive Function Coach','CARE',['executive functioning coach'],['Executive function plan','Routine milestones']),
  add('ACADEMIC_COACH','Academic Coach','CARE',['study coach'],['Academic success plan','Study milestones']),
  add('TUTOR','Private Tutor','CARE',['academic tutor'],['Learning plan','Skill milestones']),
  add('MUSIC_TEACHER','Private Music Teacher','CARE',['music instructor'],['Practice plan','Repertoire milestones']),
  add('VOICE_COACH','Voice Coach','CARE',['vocal coach'],['Voice development plan','Technique milestones']),
  add('DOG_TRAINER','Dog Trainer','CARE',['canine trainer'],['Training plan','Behavior milestones']),
  add('PET_BEHAVIOR_CONSULTANT','Pet Behavior Consultant','CARE',['animal behaviorist'],['Behavior plan','Training progress'])
]

export const SPECIALTIES = [...CORE_SPECIALTIES.filter((item) => item.key !== 'GENERAL_SERVICE_PROVIDER'), ...EXPANDED_SPECIALTIES, CORE_SPECIALTIES.find((item) => item.key === 'GENERAL_SERVICE_PROVIDER')]
export const SPECIALTY_BY_KEY = Object.fromEntries(SPECIALTIES.map((item) => [item.key, item]))
export function specialtyForKey(key) { return SPECIALTY_BY_KEY[key] || SPECIALTY_BY_KEY.GENERAL_SERVICE_PROVIDER }
export function familyForSpecialty(key) { const item = specialtyForKey(key); return WORKFLOW_FAMILIES[item.family] || WORKFLOW_FAMILIES.CARE }
export function matchesSpecialty(item, query = '') { const q = query.trim().toLowerCase(); if (!q) return true; return [item.label, ...(item.aliases || [])].some((v) => v.toLowerCase().includes(q)) }
export function templatePlansForSpecialty(key) { const item = specialtyForKey(key); if (item.samplePlans?.length) return item.samplePlans; const family = familyForSpecialty(key); return [`${item.planLabel || family.workspace} 1`, `${family.progress} follow-up`] }
export function specialtyFromProviderType(providerType = '') { const q = providerType.trim().toLowerCase(); if (!q) return SPECIALTY_BY_KEY.GENERAL_SERVICE_PROVIDER; return SPECIALTIES.find((item) => [item.label, ...(item.aliases || [])].some((v) => v.toLowerCase() === q)) || SPECIALTIES.find((item) => [item.label, ...(item.aliases || [])].some((v) => q.includes(v.toLowerCase().replace(' specialist','').replace(' provider','')))) || SPECIALTY_BY_KEY.GENERAL_SERVICE_PROVIDER }
